import type { CatalogEntry } from './playground.types';

export const catalogEntries: CatalogEntry[] = [
  {
    count: 22,
    description: 'Surface and cut primitives',
    id: 'surfaces',
    label: 'Surfaces',
    path: '/components/surfaces',
  },
  {
    count: 32,
    description: 'Action states and geometry',
    id: 'button',
    label: 'Button',
    path: '/components/button',
  },
  {
    count: 12,
    description: 'Mutually exclusive segment buttons',
    id: 'segmented',
    label: 'Segmented',
    path: '/components/segmented',
  },
  {
    count: 8,
    description: 'Surface-backed action bar',
    id: 'toolbar',
    label: 'Toolbar',
    path: '/components/toolbar',
  },
  {
    count: 8,
    description: 'Self-managing pressed button group',
    id: 'toggle-group',
    label: 'Toggle group',
    path: '/components/toggle-group',
  },
  {
    count: 23,
    description: 'Compact status language',
    id: 'chip',
    label: 'Chip',
    path: '/components/chip',
  },
  {
    count: 29,
    description: 'Continuous numeric control',
    id: 'slider',
    label: 'Slider',
    path: '/components/slider',
  },
  {
    count: 24,
    description: 'Choice control with native form participation',
    id: 'checkbox',
    label: 'Checkbox',
    path: '/components/checkbox',
  },
  {
    count: 18,
    description: 'Keyboard-first option picker',
    id: 'select',
    label: 'Select',
    path: '/components/select',
  },
  {
    count: 6,
    description: 'Portalled dialog with focus management',
    id: 'dialog',
    label: 'Dialog',
    path: '/components/dialog',
  },
  {
    count: 8,
    description: 'Anchored floating panel',
    id: 'popover',
    label: 'Popover',
    path: '/components/popover',
  },
  {
    count: 3,
    description: 'Hover/focus label',
    id: 'tooltip',
    label: 'Tooltip',
    path: '/components/tooltip',
  },
  {
    count: 18,
    description: 'Loading and progress states',
    id: 'spinner',
    label: 'Spinner',
    path: '/components/spinner',
  },
  {
    count: 10,
    description: 'Keyboard-navigable tablist',
    id: 'tabs',
    label: 'Tabs',
    path: '/components/tabs',
  },
  {
    count: 8,
    description: 'Disclosure groups',
    id: 'accordion',
    label: 'Accordion',
    path: '/components/accordion',
  },
  {
    count: 10,
    description: 'Month grid and date triggers',
    id: 'calendar',
    label: 'Calendar',
    path: '/components/calendar',
  },
  {
    count: 16,
    description: 'Colour editing and gradients',
    id: 'color',
    label: 'Color',
    path: '/components/color',
  },
  {
    count: 8,
    description: 'Text-weight polymorphic action',
    id: 'link',
    label: 'Link',
    path: '/components/link',
  },
  {
    count: 14,
    description: 'Steppers and drag-to-scrub numerics',
    id: 'numbers',
    label: 'Numbers',
    path: '/components/numbers',
  },
  {
    count: 12,
    description: 'One-time code entry',
    id: 'otp',
    label: 'OTP field',
    path: '/components/otp',
  },
  {
    component: 'Backdrop',
    count: 2,
    description: 'Dim layer behind overlays',
    id: 'backdrop',
    label: 'Backdrop',
    path: '/components/backdrop',
    title: 'Backdrop',
  },
  {
    component: 'Collapsible',
    count: 5,
    description: 'Single disclosure primitive',
    id: 'collapsible',
    label: 'Collapsible',
    path: '/components/collapsible',
    title: 'Collapsible',
  },
  {
    component: 'Input',
    count: 5,
    description: 'Text entry with cut geometry',
    id: 'input',
    label: 'Input',
    path: '/components/input',
    title: 'Input',
  },
  {
    component: 'List',
    count: 6,
    description: 'Vertical stacks for actions',
    id: 'list',
    label: 'List',
    path: '/components/list',
    title: 'List',
  },
  {
    component: 'Popup',
    count: 4,
    description: 'Full-viewport modal',
    id: 'popup',
    label: 'Popup',
    path: '/components/popup',
    title: 'Popup',
  },
  {
    component: 'Radio',
    count: 5,
    description: 'Single-choice with name grouping',
    id: 'radio',
    label: 'Radio',
    path: '/components/radio',
    title: 'Radio',
  },
  {
    component: 'SearchField',
    count: 4,
    description: 'Input specialized for searching',
    id: 'search-field',
    label: 'Search field',
    path: '/components/search-field',
    title: 'Search field',
  },
  {
    component: 'SectionTitle',
    count: 3,
    description: 'Eyebrow headers for lists',
    id: 'section-title',
    label: 'Section title',
    path: '/components/section-title',
    title: 'Section title',
  },
  {
    component: 'Shortcut',
    count: 4,
    description: 'Keycaps for shortcuts',
    id: 'shortcut',
    label: 'Shortcut',
    path: '/components/shortcut',
    title: 'Shortcut',
  },
  {
    component: 'Switch',
    count: 5,
    description: 'Two-state thumb track',
    id: 'switch',
    label: 'Switch',
    path: '/components/switch',
    title: 'Switch',
  },
  {
    component: 'Textarea',
    count: 5,
    description: 'Multi-line contenteditable field',
    id: 'textarea',
    label: 'Textarea',
    path: '/components/textarea',
    title: 'Textarea',
  },
  {
    component: 'Toast',
    count: 4,
    description: 'Stacking viewport notifications',
    id: 'toast',
    label: 'Toast',
    path: '/components/toast',
    title: 'Toast',
  },

  // --- Cladd extensions: new families built from Cladd foundations, not upstream ports. ---
  {
    component: 'Field',
    count: 4,
    description: 'Accessible label/description/error composition',
    id: 'field',
    label: 'Field',
    origin: 'extension',
    path: '/components/field',
    title: 'Field',
  },
  {
    component: 'InputGroup',
    count: 3,
    description: 'Addon and inline-action composition',
    id: 'input-group',
    label: 'Input group',
    origin: 'extension',
    path: '/components/input-group',
    title: 'Input group',
  },
  {
    component: 'Table',
    count: 8,
    description: 'Semantic table primitives',
    id: 'table',
    label: 'Table',
    origin: 'extension',
    path: '/components/table',
    title: 'Table',
  },
  {
    component: 'Table',
    count: 4,
    description: 'Consumer-owned recipe: TanStack Table state, Cladd Table DOM',
    id: 'data-table',
    label: 'Data table (TanStack)',
    origin: 'extension',
    path: '/components/data-table',
    title: 'Data table (TanStack)',
  },
  {
    component: 'DropdownMenu',
    count: 8,
    description: 'Keyboard-first action menu',
    id: 'dropdown-menu',
    label: 'Dropdown menu',
    origin: 'extension',
    path: '/components/dropdown-menu',
    title: 'Dropdown menu',
  },
  {
    component: 'ContextMenu',
    count: 4,
    description: 'Pointer-anchored context actions',
    id: 'context-menu',
    label: 'Context menu',
    origin: 'extension',
    path: '/components/context-menu',
    title: 'Context menu',
  },
  {
    component: 'Sheet',
    count: 5,
    description: 'Modal side panel',
    id: 'sheet',
    label: 'Sheet',
    origin: 'extension',
    path: '/components/sheet',
    title: 'Sheet',
  },
  {
    component: 'Drawer',
    count: 3,
    description: 'Bottom-oriented touch-aware mobile panel',
    id: 'drawer',
    label: 'Drawer',
    origin: 'extension',
    path: '/components/drawer',
    title: 'Drawer',
  },
  {
    component: 'AlertDialog',
    count: 3,
    description: 'Destructive-confirmation dialog',
    id: 'alert-dialog',
    label: 'Alert Dialog',
    origin: 'extension',
    path: '/components/alert-dialog',
    title: 'Alert Dialog',
  },
  {
    component: 'Sidebar',
    count: 6,
    description: 'Responsive application shell with nested navigation',
    id: 'sidebar',
    label: 'Sidebar',
    origin: 'extension',
    path: '/components/sidebar',
    title: 'Sidebar',
  },
  {
    component: 'Command',
    count: 4,
    description: 'Keyboard-first action discovery',
    id: 'command',
    label: 'Command',
    origin: 'extension',
    path: '/components/command',
    title: 'Command',
  },
  {
    component: 'Combobox',
    count: 5,
    description: 'Editable single and multiple entity selection',
    id: 'combobox',
    label: 'Combobox',
    origin: 'extension',
    path: '/components/combobox',
    title: 'Combobox',
  },
  {
    component: 'Breadcrumb',
    count: 4,
    description: 'Router-agnostic hierarchical location trail',
    id: 'breadcrumb',
    label: 'Breadcrumb',
    origin: 'extension',
    path: '/components/breadcrumb',
    title: 'Breadcrumb',
  },
  {
    component: 'Pagination',
    count: 4,
    description: 'Controlled result-set navigation',
    id: 'pagination',
    label: 'Pagination',
    origin: 'extension',
    path: '/components/pagination',
    title: 'Pagination',
  },
  {
    component: 'Alert',
    count: 5,
    description: 'Passive status region styled after Toast',
    id: 'alert',
    label: 'Alert',
    origin: 'extension',
    path: '/components/alert',
    title: 'Alert',
  },
  {
    component: 'Empty',
    count: 1,
    description: 'No-data, no-results, or first-run state',
    id: 'empty',
    label: 'Empty',
    origin: 'extension',
    path: '/components/empty',
    title: 'Empty',
  },
  {
    component: 'Skeleton',
    count: 1,
    description: 'Layout-preserving loading placeholder',
    id: 'skeleton',
    label: 'Skeleton',
    origin: 'extension',
    path: '/components/skeleton',
    title: 'Skeleton',
  },
  {
    component: 'Progress',
    count: 4,
    description: 'Determinate and indeterminate progress',
    id: 'progress',
    label: 'Progress',
    origin: 'extension',
    path: '/components/progress',
    title: 'Progress',
  },
  {
    component: 'Card',
    count: 2,
    description: 'Semantic structure over Surface',
    id: 'card',
    label: 'Card',
    origin: 'extension',
    path: '/components/card',
    title: 'Card',
  },
  {
    component: 'Avatar',
    count: 3,
    description: 'Zero-layout-shift identity marker',
    id: 'avatar',
    label: 'Avatar',
    origin: 'extension',
    path: '/components/avatar',
    title: 'Avatar',
  },
  {
    component: 'Separator',
    count: 2,
    description: 'Horizontal or vertical rule',
    id: 'separator',
    label: 'Separator',
    origin: 'extension',
    path: '/components/separator',
    title: 'Separator',
  },
  {
    component: 'ScrollArea',
    count: 3,
    description: 'Themed native overflow scrolling',
    id: 'scroll-area',
    label: 'Scroll area',
    origin: 'extension',
    path: '/components/scroll-area',
    title: 'Scroll area',
  },
  {
    component: 'NativeSelect',
    count: 4,
    description: 'Themed native select/option/optgroup',
    id: 'native-select',
    label: 'Native select',
    origin: 'extension',
    path: '/components/native-select',
    title: 'Native select',
  },
];

export const catalogComponentCount = 65;
export const catalogStateCount = catalogEntries.reduce(
  (sum, entry) => sum + entry.count,
  0,
);
