import type { CatalogEntry } from './playground.types';

export const catalogEntries: CatalogEntry[] = [
  {
    count: 22,
    description: 'Surface and cut primitives',
    id: 'surfaces',
    label: 'Surfaces',
    path: '/components/surfaces',
  },
  {
    count: 32,
    description: 'Action states and geometry',
    id: 'button',
    label: 'Button',
    path: '/components/button',
  },
  {
    count: 12,
    description: 'Mutually exclusive segment buttons',
    id: 'segmented',
    label: 'Segmented',
    path: '/components/segmented',
  },
  {
    count: 8,
    description: 'Surface-backed action bar',
    id: 'toolbar',
    label: 'Toolbar',
    path: '/components/toolbar',
  },
  {
    count: 8,
    description: 'Self-managing pressed button group',
    id: 'toggle-group',
    label: 'Toggle group',
    path: '/components/toggle-group',
  },
  {
    count: 23,
    description: 'Compact status language',
    id: 'chip',
    label: 'Chip',
    path: '/components/chip',
  },
  {
    count: 29,
    description: 'Continuous numeric control',
    id: 'slider',
    label: 'Slider',
    path: '/components/slider',
  },
  {
    count: 24,
    description: 'Choice control with native form participation',
    id: 'checkbox',
    label: 'Checkbox',
    path: '/components/checkbox',
  },
  {
    count: 18,
    description: 'Keyboard-first option picker',
    id: 'select',
    label: 'Select',
    path: '/components/select',
  },
  {
    count: 6,
    description: 'Portalled dialog with focus management',
    id: 'dialog',
    label: 'Dialog',
    path: '/components/dialog',
  },
  {
    count: 8,
    description: 'Anchored floating panel',
    id: 'popover',
    label: 'Popover',
    path: '/components/popover',
  },
  {
    count: 3,
    description: 'Hover/focus label',
    id: 'tooltip',
    label: 'Tooltip',
    path: '/components/tooltip',
  },
  {
    count: 18,
    description: 'Loading and progress states',
    id: 'spinner',
    label: 'Spinner',
    path: '/components/spinner',
  },
  {
    count: 10,
    description: 'Keyboard-navigable tablist',
    id: 'tabs',
    label: 'Tabs',
    path: '/components/tabs',
  },
  {
    count: 8,
    description: 'Disclosure groups',
    id: 'accordion',
    label: 'Accordion',
    path: '/components/accordion',
  },
  {
    count: 10,
    description: 'Month grid and date triggers',
    id: 'calendar',
    label: 'Calendar',
    path: '/components/calendar',
  },
  {
    count: 16,
    description: 'Colour editing and gradients',
    id: 'color',
    label: 'Color',
    path: '/components/color',
  },
  {
    count: 8,
    description: 'Text-weight polymorphic action',
    id: 'link',
    label: 'Link',
    path: '/components/link',
  },
  {
    count: 14,
    description: 'Steppers and drag-to-scrub numerics',
    id: 'numbers',
    label: 'Numbers',
    path: '/components/numbers',
  },
  {
    count: 12,
    description: 'One-time code entry',
    id: 'otp',
    label: 'OTP field',
    path: '/components/otp',
  },
  {
    component: 'Backdrop',
    count: 2,
    description: 'Dim layer behind overlays',
    id: 'backdrop',
    label: 'Backdrop',
    path: '/components/backdrop',
    title: 'Backdrop',
  },
  {
    component: 'Collapsible',
    count: 5,
    description: 'Single disclosure primitive',
    id: 'collapsible',
    label: 'Collapsible',
    path: '/components/collapsible',
    title: 'Collapsible',
  },
  {
    component: 'Input',
    count: 5,
    description: 'Text entry with cut geometry',
    id: 'input',
    label: 'Input',
    path: '/components/input',
    title: 'Input',
  },
  {
    component: 'List',
    count: 6,
    description: 'Vertical stacks for actions',
    id: 'list',
    label: 'List',
    path: '/components/list',
    title: 'List',
  },
  {
    component: 'Popup',
    count: 4,
    description: 'Full-viewport modal',
    id: 'popup',
    label: 'Popup',
    path: '/components/popup',
    title: 'Popup',
  },
  {
    component: 'Radio',
    count: 5,
    description: 'Single-choice with name grouping',
    id: 'radio',
    label: 'Radio',
    path: '/components/radio',
    title: 'Radio',
  },
  {
    component: 'SearchField',
    count: 4,
    description: 'Input specialized for searching',
    id: 'search-field',
    label: 'Search field',
    path: '/components/search-field',
    title: 'Search field',
  },
  {
    component: 'SectionTitle',
    count: 3,
    description: 'Eyebrow headers for lists',
    id: 'section-title',
    label: 'Section title',
    path: '/components/section-title',
    title: 'Section title',
  },
  {
    component: 'Shortcut',
    count: 4,
    description: 'Keycaps for shortcuts',
    id: 'shortcut',
    label: 'Shortcut',
    path: '/components/shortcut',
    title: 'Shortcut',
  },
  {
    component: 'Switch',
    count: 5,
    description: 'Two-state thumb track',
    id: 'switch',
    label: 'Switch',
    path: '/components/switch',
    title: 'Switch',
  },
  {
    component: 'Textarea',
    count: 5,
    description: 'Multi-line contenteditable field',
    id: 'textarea',
    label: 'Textarea',
    path: '/components/textarea',
    title: 'Textarea',
  },
  {
    component: 'Toast',
    count: 4,
    description: 'Stacking viewport notifications',
    id: 'toast',
    label: 'Toast',
    path: '/components/toast',
    title: 'Toast',
  },
];

export const catalogComponentCount = 54;
export const catalogStateCount = catalogEntries.reduce(
  (sum, entry) => sum + entry.count,
  0,
);
